import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import { defineComponent, h } from 'vue'
import CatField from './field.vue'
import CatInput from './input.vue'

// Verifies the claim in catenary issue #9 — that the IDs generated by Vue 3.5's
// useId() inside cat-field were not unique. With Vue 3.5+ this should hold true
// for any mix of fields rendered in the same app instance.
describe('cat-field fieldId uniqueness', () => {
  it('generates a unique fieldId per cat-field instance', () => {
    const Harness = defineComponent({
      components: { CatField, CatInput },
      setup () {
        return () => h('div', [
          h(CatField, { label: 'A' }, () => h(CatInput, { modelValue: '' })),
          h(CatField, { label: 'B' }, () => h(CatInput, { modelValue: '' })),
          h(CatField, { label: 'C' }, () => h(CatInput, { modelValue: '' }))
        ])
      }
    })

    const wrapper = mount(Harness)
    const labels = wrapper.findAll('label.label')
    const inputs = wrapper.findAll('input.input')

    expect(labels).toHaveLength(3)
    expect(inputs).toHaveLength(3)

    const fors = labels.map(l => l.attributes('for'))
    const ids = inputs.map(i => i.attributes('id'))

    // Each label's `for` must match its sibling input's `id`
    expect(fors).toEqual(ids)
    // Every id must be defined
    expect(ids.every(id => typeof id === 'string' && id.length > 0)).toBe(true)
    // All ids must be distinct
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('preserves uniqueness across many cat-fields in the same render', () => {
    const Harness = defineComponent({
      components: { CatField, CatInput },
      setup () {
        return () => h('div', Array.from({ length: 25 }, (_, i) => (
          h(CatField, { key: i, label: `Field ${i}` }, () => h(CatInput, { modelValue: '' }))
        )))
      }
    })

    const wrapper = mount(Harness)
    const ids = wrapper.findAll('input.input').map(i => i.attributes('id'))

    expect(ids).toHaveLength(25)
    expect(new Set(ids).size).toBe(25)
  })
})

describe('cat-field message association', () => {
  function mountFieldWithInput (fieldProps: Record<string, any> = {}, inputProps: Record<string, any> = {}) {
    const Harness = defineComponent({
      components: { CatField, CatInput },
      setup () {
        return () => h(CatField, { label: 'Start date', ...fieldProps }, () => h(CatInput, { modelValue: '', ...inputProps }))
      }
    })
    return mount(Harness)
  }

  it('associates the help message with the control via aria-describedby', () => {
    const wrapper = mountFieldWithInput({ message: 'Dates must be within the archive range' })
    const input = wrapper.find('input')
    const describedby = input.attributes('aria-describedby')
    expect(describedby).toBeTruthy()
    const help = wrapper.find(`[id="${describedby}"]`)
    expect(help.text()).toBe('Dates must be within the archive range')
  })

  it('omits aria-describedby when there is no message', () => {
    const wrapper = mountFieldWithInput()
    expect(wrapper.find('input').attributes('aria-describedby')).toBeUndefined()
  })

  it('merges the field message with the control\'s own ariaDescribedby', () => {
    const wrapper = mountFieldWithInput({ message: 'Out of range' }, { ariaDescribedby: 'format-hint' })
    const describedby = wrapper.find('input').attributes('aria-describedby')
    expect(describedby?.split(' ')).toContain('format-hint')
    expect(describedby?.split(' ').length).toBe(2)
  })

  it('marks the control aria-invalid when the field variant is danger', () => {
    const wrapper = mountFieldWithInput({ message: 'Bad value', variant: 'danger' })
    expect(wrapper.find('input').attributes('aria-invalid')).toBe('true')

    const ok = mountFieldWithInput({ message: 'All good', variant: 'success' })
    expect(ok.find('input').attributes('aria-invalid')).toBeUndefined()
  })

  it('marks the control aria-invalid from its own danger variant', () => {
    const wrapper = mountFieldWithInput({}, { variant: 'danger' })
    expect(wrapper.find('input').attributes('aria-invalid')).toBe('true')
  })
})
