import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import { defineComponent, h } from 'vue'
import CatField from './field.vue'
import CatInput from './input.vue'

// Verifies the claim in catenary issue #9 — that the IDs generated by Vue 3.5's
// useId() inside cat-field were not unique. With Vue 3.5+ this should hold true
// for any mix of fields rendered in the same app instance.
describe('cat-field fieldId uniqueness', () => {
  it('generates a unique fieldId per cat-field instance', () => {
    const Harness = defineComponent({
      components: { CatField, CatInput },
      setup () {
        return () => h('div', [
          h(CatField, { label: 'A' }, () => h(CatInput, { modelValue: '' })),
          h(CatField, { label: 'B' }, () => h(CatInput, { modelValue: '' })),
          h(CatField, { label: 'C' }, () => h(CatInput, { modelValue: '' }))
        ])
      }
    })

    const wrapper = mount(Harness)
    const labels = wrapper.findAll('label.label')
    const inputs = wrapper.findAll('input.input')

    expect(labels).toHaveLength(3)
    expect(inputs).toHaveLength(3)

    const fors = labels.map(l => l.attributes('for'))
    const ids = inputs.map(i => i.attributes('id'))

    // Each label's `for` must match its sibling input's `id`
    expect(fors).toEqual(ids)
    // Every id must be defined
    expect(ids.every(id => typeof id === 'string' && id.length > 0)).toBe(true)
    // All ids must be distinct
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('preserves uniqueness across many cat-fields in the same render', () => {
    const Harness = defineComponent({
      components: { CatField, CatInput },
      setup () {
        return () => h('div', Array.from({ length: 25 }, (_, i) => (
          h(CatField, { key: i, label: `Field ${i}` }, () => h(CatInput, { modelValue: '' }))
        )))
      }
    })

    const wrapper = mount(Harness)
    const ids = wrapper.findAll('input.input').map(i => i.attributes('id'))

    expect(ids).toHaveLength(25)
    expect(new Set(ids).size).toBe(25)
  })
})
